# This is a basic workflow to help you get started with Actions

name: Prettier of the CSS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["dev", "dev-test-actions"]
  pull_request:
    branches: ["dev", "dev-test-actions"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.9.2"
      - run: auto.py
      - name: Prettier Action
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{css,md}
          commit_message: "Test"
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev-test-actions
